FROM php:8.1-fpm

# Устанавливаем необходимые зависимости и расширения PHP
#RUN apt-get update && apt-get install -y libzip-dev zip

RUN apt-get update && apt-get install -y \
    openssl \
    libpng-dev \
    libjpeg-dev \
    libfreetype6-dev \
    libzip-dev \
    zip  \
    unzip \
    default-mysql-client \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install pdo_mysql gd zip

WORKDIR /var/www

EXPOSE 9000

CMD ["php-fpm"]
